---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anish-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anish-two
  template:
    metadata:
      labels:
        app: anish-two
    spec:
      containers:
      - name: anish-two
        image: 8857890900/anish_two

        ports:
        - containerPort: 8080
        env:
          - name: PORT
