--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: anish-web-application
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: anish-web-application
  template: 
    metadata: 
      labels: 
        app: anish-web-application
    spec: 
      containers: 
      - name: anish-web-application
        image: 8857890900/anish_webserver
          
        ports: 
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
