--- 
apiVersion: v1
kind: Service
metadata: 
  name: anish-web-application
spec: 
  ports: 
    - 
      port: 80
      protocol: TCP
      targetPort: 8080
  selector: 
    app: anish-web-application
  type: LoadBalancer
